### ISSUE TITLE
FWIW

### ISSUE THREAD

**Issue by drvinceknight** [alcarney/polynomial_chaos#1]
Please feel free not to use: https://github.com/drvinceknight/CU_BSc_LaTeX_Template

Also, I don't necessarily recommend `make` for `tex`, take a look at `latexmk`

**Comment by alcarney** [comment]
Cool thanks :)

**Comment by alcarney** [comment]
@drvinceknight what is `tex/main.run.xml` file for in the template repoistory?

**Comment by drvinceknight** [comment]
It's an auxilary file. Should have been gitignored. I think it's spat out
by latexmk. Not sure.

**Comment by alcarney** [comment]
Thanks
